Improves security when processing properties files (#2303)
* Improves security when processing properties files

* Check for spaces in the key

---------

Co-authored-by: Anthony Stirling <77850077+Frooodle@users.noreply.github.com>

diff --git a/.github/workflows/check_properties.yml b/.github/workflows/check_properties.yml
--- a/.github/workflows/check_properties.yml
+++ b/.github/workflows/check_properties.yml
@@ -50,10 +50,7 @@ jobs:
           echo "Getting list of changed files from PR..."
           gh pr view ${{ github.event.pull_request.number }} --json files -q ".files[].path" | grep -E '^src/main/resources/messages_[a-zA-Z_]+\.properties$' > ../changed_files.txt
           cd ..
-          echo "Setting branch path..."
-          BRANCH_PATH="pr-branch"
 
-          echo "BRANCH_PATH=${BRANCH_PATH}" >> $GITHUB_ENV
           echo "Processing changed files..."
           mapfile -t CHANGED_FILES < changed_files.txt
 
@@ -61,7 +58,6 @@ jobs:
           echo "CHANGED_FILES=${CHANGED_FILES_STR}" >> $GITHUB_ENV
 
           echo "Changed files: ${CHANGED_FILES_STR}"
-          echo "Branch: ${BRANCH_PATH}"
 
       - name: Determine reference file
         id: determine-file
@@ -85,30 +81,38 @@ jobs:
           python main-branch/.github/scripts/check_language_properties.py \
             --actor ${{ github.event.pull_request.user.login }} \
             --reference-file "${REFERENCE_FILE}" \
-            --branch "${BRANCH_PATH}" \
-            --files "${CHANGED_FILES[@]}" > failure.txt || true
+            --branch pr-branch \
+            --files "${CHANGED_FILES[@]}" > result.txt || true
 
       - name: Capture output
         id: capture-output
         run: |
-          if [ -f failure.txt ] && [ -s failure.txt ]; then
-            echo "Test failed, capturing output..."
-            ERROR_OUTPUT=$(cat failure.txt)
-            echo "ERROR_OUTPUT<<EOF" >> $GITHUB_ENV
-            echo "$ERROR_OUTPUT" >> $GITHUB_ENV
+          if [ -f result.txt ] && [ -s result.txt ]; then
+            echo "Test, capturing output..."
+            SCRIPT_OUTPUT=$(cat result.txt)
+            echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
+            echo "$SCRIPT_OUTPUT" >> $GITHUB_ENV
             echo "EOF" >> $GITHUB_ENV
-            echo "${ERROR_OUTPUT}"
+            echo "${SCRIPT_OUTPUT}"
+
+            # Set FAIL_JOB to true if SCRIPT_OUTPUT contains ❌
+            if [[ "$SCRIPT_OUTPUT" == *"❌"* ]]; then
+              echo "FAIL_JOB=true" >> $GITHUB_ENV
+            else
+              echo "FAIL_JOB=false" >> $GITHUB_ENV
+            fi
           else
-            echo "No errors found."
-            echo "ERROR_OUTPUT=" >> $GITHUB_ENV
+            echo "No update found."
+            echo "SCRIPT_OUTPUT=" >> $GITHUB_ENV
+            echo "FAIL_JOB=false" >> $GITHUB_ENV
           fi
 
       - name: Post comment on PR
-        if: env.ERROR_OUTPUT != ''
+        if: env.SCRIPT_OUTPUT != ''
         uses: actions/github-script@v7
         with:
           script: |
-            const { GITHUB_REPOSITORY, ERROR_OUTPUT } = process.env;
+            const { GITHUB_REPOSITORY, SCRIPT_OUTPUT } = process.env;
             const [repoOwner, repoName] = GITHUB_REPOSITORY.split('/');
             const prNumber = context.issue.number;
 
@@ -130,7 +134,7 @@ jobs:
                 owner: repoOwner,
                 repo: repoName,
                 comment_id: comment.id,
-                body: `## 🚀 Translation Verification Summary\n\n\n${ERROR_OUTPUT}\n`
+                body: `## 🚀 Translation Verification Summary\n\n\n${SCRIPT_OUTPUT}\n`
               });
               console.log("Updated existing comment.");
             } else if (!comment) {
@@ -139,12 +143,18 @@ jobs:
                 owner: repoOwner,
                 repo: repoName,
                 issue_number: prNumber,
-                body: `## 🚀 Translation Verification Summary\n\n\n${ERROR_OUTPUT}\n`
+                body: `## 🚀 Translation Verification Summary\n\n\n${SCRIPT_OUTPUT}\n`
               });
               console.log("Created new comment.");
             } else {
               console.log("Comment update attempt denied. Actor does not match.");
             }
+
+      - name: Fail job if errors found
+        if: env.FAIL_JOB == 'true'
+        run: |
+          echo "Failing the job because errors were detected."
+          exit 1
 
   update-translations-main:
     if: github.event_name == 'push'
